import type { CaptionCue, ScoredSentence, WordCue } from '../types';
import { formatTimecode } from '../ingest';

/**
 * Caption cutting for vertical video.
 *
 * Burn-in captions have a different constraint from broadcast subtitles: the
 * safe area is narrow, the viewer is scrolling, and a line that wraps reads as
 * a wall. We cap at `maxChars` across at most two lines, break at the latest
 * clause marker inside the budget, and never leave a one-word orphan line.
 */
const MAX_CHARS = 42;
const MIN_CUE_SEC = 0.75;
const MAX_CUE_SEC = 3.4;

/** Distribute a sentence's duration across its words by relative length. */
export function wordTimings(sentences: ScoredSentence[], clipStart: number): WordCue[] {
  const out: WordCue[] = [];

  for (const s of sentences) {
    const tokens = s.text.split(/\s+/).filter(Boolean);
    if (!tokens.length) continue;

    const span = Math.max(0.25, s.end - s.start);
    // Longer words take proportionally longer to say; a floor keeps "a" visible.
    const weights = tokens.map((t) => Math.max(2.2, t.replace(/[^\w]/g, '').length));
    const total = weights.reduce((a, b) => a + b, 0);

    let cursor = s.start - clipStart;
    tokens.forEach((word, i) => {
      const dur = (weights[i] / total) * span;
      out.push({ word, start: cursor, end: cursor + dur });
      cursor += dur;
    });
  }

  return out;
}

const BREAK_AFTER = /[,;:—–]$/;

export function buildCaptions(sentences: ScoredSentence[], clipStart: number): CaptionCue[] {
  const words = wordTimings(sentences, clipStart);
  const cues: CaptionCue[] = [];

  let buffer: WordCue[] = [];
  const flush = () => {
    if (!buffer.length) return;
    const text = buffer.map((w) => w.word).join(' ');
    cues.push({
      index: cues.length + 1,
      start: buffer[0].start,
      end: Math.max(buffer[buffer.length - 1].end, buffer[0].start + MIN_CUE_SEC),
      text: wrap(text),
    });
    buffer = [];
  };

  for (const w of words) {
    const projected = buffer.map((b) => b.word).join(' ') + (buffer.length ? ' ' : '') + w.word;
    const span = buffer.length ? w.end - buffer[0].start : 0;

    if (buffer.length && (projected.length > MAX_CHARS || span > MAX_CUE_SEC)) flush();
    buffer.push(w);

    const trimmed = w.word.replace(/["')\]]+$/, '');
    if (/[.!?]$/.test(trimmed)) { flush(); continue; }
    // A comma late in the budget is a better break than a hard character cut.
    if (BREAK_AFTER.test(trimmed) && projected.length > MAX_CHARS * 0.6) flush();
  }
  flush();

  // Close gaps so captions never flicker off between cues.
  for (let i = 0; i < cues.length - 1; i++) {
    if (cues[i + 1].start - cues[i].end < 0.24) cues[i].end = cues[i + 1].start;
  }

  return cues;
}

/** Break one cue across two balanced lines rather than letting the player wrap it. */
function wrap(text: string): string {
  if (text.length <= 24) return text;
  const words = text.split(' ');
  let best = text;
  let bestDelta = Infinity;

  for (let i = 1; i < words.length; i++) {
    const a = words.slice(0, i).join(' ');
    const b = words.slice(i).join(' ');
    if (a.length > MAX_CHARS || b.length > MAX_CHARS) continue;
    // Balanced lines, and never a single short orphan on line two.
    const delta = Math.abs(a.length - b.length) + (b.split(' ').length === 1 ? 12 : 0);
    if (delta < bestDelta) { bestDelta = delta; best = `${a}\n${b}`; }
  }
  return best;
}

export function toSRT(cues: CaptionCue[]): string {
  return cues
    .map((c) =>
      [
        String(c.index),
        `${formatTimecode(c.start, { ms: true, comma: true })} --> ${formatTimecode(c.end, { ms: true, comma: true })}`,
        c.text,
        '',
      ].join('\n'),
    )
    .join('\n');
}

export function toVTT(cues: CaptionCue[]): string {
  const body = cues
    .map((c) =>
      [
        `${formatTimecode(c.start, { ms: true })} --> ${formatTimecode(c.end, { ms: true })} line:82% align:center`,
        c.text,
        '',
      ].join('\n'),
    )
    .join('\n');
  return `WEBVTT\n\nNOTE Generated by HOOKLINE — positioned for vertical safe area.\n\n${body}`;
}
