#!/usr/bin/env bash
# Generated by HOOKLINE. Cuts every clip from the source recording and burns in captions.
# Usage: ./cut.sh /path/to/source-video.mp4
set -euo pipefail
SRC="${1:?pass the source video as the first argument}"
OUT="$(cd "$(dirname "$0")" && pwd)/rendered"
mkdir -p "$OUT"

# clip-01 — Everybody tells you the algorithm decides who wins.
ffmpeg -y -ss 2.400 -to 53.996 -i "$SRC" \
  -vf "crop=ih*9/16:ih,scale=1080:1920,subtitles=$(printf %q "captions/clip-01.srt"):force_style='Fontsize=17,Outline=2,Alignment=2,MarginV=140'" \
  -c:a aac -b:a 192k -c:v libx264 -preset slow -crf 20 "$OUT/clip-01.mp4"

# clip-02 — Nobody arrives at your clip having watched the previous nine minutes.
ffmpeg -y -ss 384.434 -to 403.072 -i "$SRC" \
  -vf "crop=ih*9/16:ih,scale=1080:1920,subtitles=$(printf %q "captions/clip-02.srt"):force_style='Fontsize=17,Outline=2,Alignment=2,MarginV=140'" \
  -c:a aac -b:a 192k -c:v libx264 -preset slow -crf 20 "$OUT/clip-02.mp4"

# clip-03 — "Everybody tells you the algorithm decides who wins" is not dead.
ffmpeg -y -ss 432.069 -to 467.761 -i "$SRC" \
  -vf "crop=ih*9/16:ih,scale=1080:1920,subtitles=$(printf %q "captions/clip-03.srt"):force_style='Fontsize=17,Outline=2,Alignment=2,MarginV=140'" \
  -c:a aac -b:a 192k -c:v libx264 -preset slow -crf 20 "$OUT/clip-03.mp4"

# clip-04 — The reason is that for the first time in four years I said something.
ffmpeg -y -ss 90.660 -to 120.314 -i "$SRC" \
  -vf "crop=ih*9/16:ih,scale=1080:1920,subtitles=$(printf %q "captions/clip-04.srt"):force_style='Fontsize=17,Outline=2,Alignment=2,MarginV=140'" \
  -c:a aac -b:a 192k -c:v libx264 -preset slow -crf 20 "$OUT/clip-04.mp4"

# clip-05 — If you spent an hour saying nothing, no amount of clipping finds the m
ffmpeg -y -ss 520.195 -to 542.437 -i "$SRC" \
  -vf "crop=ih*9/16:ih,scale=1080:1920,subtitles=$(printf %q "captions/clip-05.srt"):force_style='Fontsize=17,Outline=2,Alignment=2,MarginV=140'" \
  -c:a aac -b:a 192k -c:v libx264 -preset slow -crf 20 "$OUT/clip-05.mp4"

# clip-06 — If it is already known, there is no reason to keep watching.
ffmpeg -y -ss 159.178 -to 178.732 -i "$SRC" \
  -vf "crop=ih*9/16:ih,scale=1080:1920,subtitles=$(printf %q "captions/clip-06.srt"):force_style='Fontsize=17,Outline=2,Alignment=2,MarginV=140'" \
  -c:a aac -b:a 192k -c:v libx264 -preset slow -crf 20 "$OUT/clip-06.mp4"
