#!/usr/bin/env bash
# Generated by HOOKLINE. Cuts every clip from the source recording and burns in captions.
# Usage: ./cut.sh /path/to/source-video.mp4
set -euo pipefail
SRC="${1:?pass the source video as the first argument}"
OUT="$(cd "$(dirname "$0")" && pwd)/rendered"
mkdir -p "$OUT"

# clip-01 — The question everyone asks is how we shipped a product in eleven weeks
ffmpeg -y -ss 0.000 -to 18.800 -i "$SRC" \
  -vf "crop=ih*9/16:ih,scale=1080:1920,subtitles=$(printf %q "captions/clip-01.srt"):force_style='Fontsize=17,Outline=2,Alignment=2,MarginV=140'" \
  -c:a aac -b:a 192k -c:v libx264 -preset slow -crf 20 "$OUT/clip-01.mp4"

# clip-02 — What finally broke it was that we ran out of money.
ffmpeg -y -ss 175.000 -to 218.100 -i "$SRC" \
  -vf "crop=ih*9/16:ih,scale=1080:1920,subtitles=$(printf %q "captions/clip-02.srt"):force_style='Fontsize=17,Outline=2,Alignment=2,MarginV=140'" \
  -c:a aac -b:a 192k -c:v libx264 -preset slow -crf 20 "$OUT/clip-02.mp4"

# clip-03 — We worked genuinely unreasonable hours for the first year.
ffmpeg -y -ss 233.200 -to 259.950 -i "$SRC" \
  -vf "crop=ih*9/16:ih,scale=1080:1920,subtitles=$(printf %q "captions/clip-03.srt"):force_style='Fontsize=17,Outline=2,Alignment=2,MarginV=140'" \
  -c:a aac -b:a 192k -c:v libx264 -preset slow -crf 20 "$OUT/clip-03.mp4"

# clip-04 — Somebody has an idea, and there is capacity, so it gets built.
ffmpeg -y -ss 31.500 -to 53.900 -i "$SRC" \
  -vf "crop=ih*9/16:ih,scale=1080:1920,subtitles=$(printf %q "captions/clip-04.srt"):force_style='Fontsize=17,Outline=2,Alignment=2,MarginV=140'" \
  -c:a aac -b:a 192k -c:v libx264 -preset slow -crf 20 "$OUT/clip-04.mp4"
