import { useState } from 'react';
import type { Analysis, Clip, SignalName } from '../../engine/types';
import { formatTimecode } from '../../engine/ingest';
import { PLATFORM_LABELS } from '../../engine/generate/titles';
import { PATTERN_LABELS } from '../../engine/generate/hooks';
import { renderThumbnailSVG } from '../../engine/generate/thumbnail';
import { corpusMean } from '../../engine/pipeline';
import { SignalBars } from './SignalBars';
import { CopyField } from './CopyField';

type Tab = 'copy' | 'captions' | 'thumbnail' | 'signals';

const TABS: { key: Tab; label: string }[] = [
  { key: 'copy', label: 'Copy' },
  { key: 'captions', label: 'Captions' },
  { key: 'thumbnail', label: 'Thumbnail' },
  { key: 'signals', label: 'Signals' },
];

export function ClipDetail({ clip, analysis }: { clip: Clip; analysis: Analysis }) {
  const [tab, setTab] = useState<Tab>('copy');
  const baseline = corpusMean(analysis);
  const withheld: SignalName[] = analysis.source.hasRealTimings ? [] : ['pace'];

  return (
    <article className="detail" aria-labelledby={`detail-${clip.id}`}>
      <header className="detail__head">
        <div className="detail__ident">
          <span className="detail__rank num">{String(clip.rank).padStart(2, '0')}</span>
          <div>
            <h3 id={`detail-${clip.id}`} className="detail__hook">{clip.hook}</h3>
            <p className="detail__meta num">
              {formatTimecode(clip.start)}–{formatTimecode(clip.end)}
              <span className="detail__dot">·</span>
              {clip.durationSec.toFixed(0)}s
              <span className="detail__dot">·</span>
              {PATTERN_LABELS[clip.hookPattern]}
              {clip.enhanced && <span className="detail__badge">Claude-rewritten</span>}
            </p>
          </div>
        </div>
        <ScoreDial score={clip.score} />
      </header>

      <p className="detail__why">
        <span className="label">Selected because</span>
        {clip.evidence.join(' · ')}
      </p>

      <nav className="tabs" role="tablist" aria-label="Clip output">
        {TABS.map((t) => (
          <button
            key={t.key}
            role="tab"
            type="button"
            aria-selected={tab === t.key}
            className={`tabs__tab${tab === t.key ? ' is-active' : ''}`}
            onClick={() => setTab(t.key)}
          >
            {t.label}
          </button>
        ))}
      </nav>

      <div className="detail__body" role="tabpanel">
        {tab === 'copy' && (
          <div className="stack">
            {clip.titles.map((t) => (
              <CopyField
                key={t.platform}
                label={PLATFORM_LABELS[t.platform]}
                value={t.text}
                meta={`${t.chars}/${t.limit}`}
                tone={t.chars > t.limit ? 'heat' : 'default'}
              />
            ))}
            <CopyField label="Description" value={clip.description} multiline />
            <CopyField label="Hashtags" value={clip.hashtags.join(' ')} />
            <div className="broll">
              <span className="label">B-roll cues</span>
              <ul className="broll__list">
                {clip.bRoll.map((b) => <li key={b}>{b}</li>)}
              </ul>
            </div>
          </div>
        )}

        {tab === 'captions' && (
          <div className="stack">
            <div className="captions__head">
              <span className="label">{clip.captions.length} cues · vertical safe area</span>
              <div className="captions__actions">
                <DownloadButton name={`${clip.id}.srt`} body={clip.srt} type="text/plain">SRT</DownloadButton>
                <DownloadButton name={`${clip.id}.vtt`} body={clip.vtt} type="text/vtt">VTT</DownloadButton>
              </div>
            </div>
            <ol className="captions">
              {clip.captions.map((cue) => (
                <li key={cue.index} className="captions__cue">
                  <span className="captions__time num">
                    {formatTimecode(cue.start, { ms: true }).slice(3)}
                  </span>
                  <span className="captions__text">
                    {cue.text.split('\n').map((l, i) => <span key={i}>{l}</span>)}
                  </span>
                </li>
              ))}
            </ol>
          </div>
        )}

        {tab === 'thumbnail' && (
          <div className="thumb">
            <div
              className="thumb__frame"
              // The SVG is generated by the engine from values it computed; no
              // user text reaches it unescaped.
              dangerouslySetInnerHTML={{ __html: renderThumbnailSVG(clip, clip.rank) }}
            />
            <div className="thumb__spec stack">
              <CopyField label="Overlay text" value={clip.thumbnail.overlay} tone="heat" />
              <div className="field">
                <span className="label">Grab frame</span>
                <p className="field__value num">{formatTimecode(clip.thumbnail.frameAtSec, { ms: true })}</p>
              </div>
              <div className="field">
                <span className="label">Composition</span>
                <p className="field__value">{clip.thumbnail.composition}</p>
              </div>
              <DownloadButton name={`${clip.id}-thumbnail.svg`} body={renderThumbnailSVG(clip, clip.rank)} type="image/svg+xml">
                Download SVG
              </DownloadButton>
            </div>
          </div>
        )}

        {tab === 'signals' && (
          <div className="stack">
            <SignalBars signals={clip.signals} baseline={baseline} withheld={withheld} />
            <div className="breakdown">
              <span className="label">Selection score, by component</span>
              <ul className="breakdown__list">
                {[
                  ['Opening', clip.breakdown.opening, 'First line, weighted hardest — the feed decides here'],
                  ['Body', clip.breakdown.body, 'Mean attention across the window'],
                  ['Payoff', clip.breakdown.payoff, 'Does it resolve rather than trail off'],
                  ['Containment', clip.breakdown.containment, 'Understandable with no prior context'],
                  ['Boundary fit', clip.breakdown.boundary, 'How close the cuts sit to a real topic change'],
                ].map(([label, value, note]) => (
                  <li key={label as string} className="breakdown__row">
                    <span className="breakdown__label">{label as string}</span>
                    <span className="breakdown__bar">
                      <span style={{ width: `${(value as number) * 100}%` }} />
                    </span>
                    <span className="breakdown__value num">{((value as number) * 100).toFixed(0)}</span>
                    <span className="breakdown__note">{note as string}</span>
                  </li>
                ))}
              </ul>
            </div>
            <details className="transcript">
              <summary>Clip transcript</summary>
              <p>{clip.transcript}</p>
            </details>
          </div>
        )}
      </div>
    </article>
  );
}

function ScoreDial({ score }: { score: number }) {
  const r = 26;
  const circumference = 2 * Math.PI * r;
  const filled = (score / 100) * circumference;

  return (
    <div className="dial" role="img" aria-label={`Selection score ${score.toFixed(0)} out of 100`}>
      <svg viewBox="0 0 64 64" width="64" height="64">
        <circle cx="32" cy="32" r={r} className="dial__track" />
        <circle
          cx="32" cy="32" r={r}
          className="dial__value"
          strokeDasharray={`${filled} ${circumference}`}
          transform="rotate(-90 32 32)"
        />
      </svg>
      <span className="dial__num num">{score.toFixed(0)}</span>
    </div>
  );
}

function DownloadButton({
  name, body, type, children,
}: { name: string; body: string; type: string; children: React.ReactNode }) {
  const download = () => {
    const blob = new Blob([body], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = name;
    a.click();
    URL.revokeObjectURL(url);
  };
  return <button type="button" className="btn btn--ghost btn--sm" onClick={download}>{children}</button>;
}
